apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: ner-uk-ms
        image: chaliy/ner-ms:uk
        ports:
        - containerPort: 8080
