.PHONY: all

RESOURCE_GROUP=play-azure-kubernetes
CLUSTER_NAME=chaliy-play-azure-kubernetes

# Create Azure Resource Group to play in
group:
	az group create -n $(RESOURCE_GROUP) -l "West Europe"

# Create Kubernetes cluster using ACS
create:
	az acs create -n $(CLUSTER_NAME) \
		-g $(RESOURCE_GROUP) \
		--admin-username ops \
		--dns-prefix $(CLUSTER_NAME) \
		--orchestrator-type kubernetes

# If something going wrang, clean up resource group
destroy:
	az group deployment create --mode complete \
		--template-file purge.json \
		--resource-group $(RESOURCE_GROUP) \
		--name Purge

# Configure kubectl with credentials generated by ACS
creds:
	az acs kubernetes get-credentials -n $(CLUSTER_NAME) \
		-g $(RESOURCE_GROUP)

 # Deploy example service
hello:
	kubectl create -f ./hello.yml
	# kubectl logs hello
	# kubectl port-forward hello 8080
	# kubectl expose deployment hello --type="LoadBalancer" --port=80 --target-port=8080
	# kubectl get services/hello

# Print some helpf information about cluster
info:
	kubectl cluster-info

# Creates proxy to the Kubernetes cluster
# You can then view dasboard locally http://localhost:8000/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard/
proxy:
	kubectl proxy --port=8000

# Scale to 5 agents. Not working for the time being
scale5:
	# Does not work, scale is not implemented at all
	az acs scale -n $(CLUSTER_NAME) \
		-g $(RESOURCE_GROUP) \
		--new-agent-count 5 \
		--debug
