apiVersion: v1
kind: Service
metadata:
  name: ner-uk
spec:
  ports:
    - port: 8080
  selector:
    app: ner-uk
    tier: services
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ner-uk
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ner-uk
        tier: services
    spec:
      containers:
      - image: chaliy/ner-ms:uk
        name: ner-uk
        ports:
        - containerPort: 8080
