apiVersion: v1
kind: Service
metadata:
  name: router
spec:
  ports:
    - port: 80
  selector:
    app: router
    tier: dmz
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: router
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: router
        tier: dmz
    spec:
      containers:
      - image: chaliy/play-azure-kubernetes-router:latest
        name: play-azure-kubernetes-router
        ports:
        - containerPort: 80
